Milestone2
bellom/calculatorwithreact pull request #3
Opened 2019-10-30 13:38 UTC by bellom

Kindly Review !

2019-10-31 14:59 UTC, SunnyAsar requested changes
# Hey @bellom  👋 
Project looking good so far.

#### For the finish:
- let up just update the display and button components.
The display needs a default value, the display and button need to have propTypes also set.

**Please request another review when these changes are in place**

2019-10-31 14:59 UTC, SunnyAsar commented on src/component/Display.js
> +      <p>{result}</p>
Hi, let us set defaultProps to make sure there is `0` displayed when there is no prop.
and also set propTypes to string

2019-10-31 14:59 UTC, SunnyAsar commented on src/component/Button.js
> +
let's set propType to string for the buttonName here too.

2019-10-31 18:03 UTC, bellom commented
**Note:** Modern React, we can always initialize our "state" without constructor.
e.g state = {firstName: ""}

2019-11-01 13:11 UTC, BalintMendli requested changes
Hi @bellom ,

Great job, but we need to set up [propTypes](https://reactjs.org/docs/typechecking-with-proptypes.html) to validate the props in Display and Button components:
* Display's result prop should be a string with a default value of '0'
* Button's name prop should be a string and it should be required

**Please add it and submit another review request.**

_If you have any questions please contact me on Slack._

2019-11-04 12:22 UTC, BalintMendli approved these changes
Hi @bellom ,

Looking good now.

### 👍 

Let's move to the next one.

2019-11-04 16:37 UTC, merged