Milestone3
bellom/calculatorwithreact pull request #4
Opened 2019-10-31 16:12 UTC by bellom

kindly review !

2019-11-04 10:40 UTC, SunnyAsar requested changes
# Hi @bellom  👋 
let's use default props to set button colour and remove the log message to make this whole.

**please request another review with the update**

2019-11-04 10:40 UTC, SunnyAsar commented on src/component/Button.js
> +  console.log(wide)
Hi, Please remove log message

2019-11-04 10:40 UTC, SunnyAsar commented on src/component/Button.js
> +  const buttonColor = color === "grey" ? "grey" : "orange"
we are supposed to use defaultProps for colour. so any button that doesn't get a prop will automatically use orange.

2019-11-04 10:40 UTC, SunnyAsar commented on src/component/Display.js
> +      <p>{result}0</p>
**Friendly reminder**
This is from the previous milestone, you are supposed to be using defaultProps and propTypes here.

2019-11-04 16:42 UTC, bellom commented on src/component/Button.js
> +  console.log(wide)
forgot ! removed now

2019-11-05 12:02 UTC, SunnyAsar approved these changes
## Looking Good!
### Hey @bellom please proceed.

# You May Pass 👍

2019-11-06 01:12 UTC, merged